version: '3.3'
services:
  orion-ops:
    build:
      context: .
      dockerfile: docker/orion-ops/Dockerfile
    image: orion-ops:1.2.3
    ports:
      - 1022:22
      - 1080:80
    environment:
      - MYSQL_HOST=orion-ops-db
      - REDIS_HOST=orion-ops-redis
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=Data@123456
    volumes:
      - /data/orion-ops-space/docker-volumns/root:/root
    depends_on:
      - orion-ops-db
      - orion-ops-redis
  orion-ops-db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    privileged: true
    environment:
      - MYSQL_DATABASE=orion-ops
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=Data@123456
      - MYSQL_ROOT_PASSWORD=Data@123456
    ports:
      - 13306:3306
    volumes:
      - /data/orion-ops-space/docker-volumns/mysql/var-lib-mysql:/var/lib/mysql
      - /data/orion-ops-space/docker-volumns/mysql/var-lib-mysql-files:/var/lib/mysql-files
      - /data/orion-ops-space/docker-volumns/mysql/etc-mysql:/etc/mysql
    image: orion-ops-db:8.0
  orion-adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
  orion-ops-redis:
    image: redis:6.0.16-alpine
    command: redis-server --requirepass Data@123456
    ports:
      - 16379:6379
